#!/bin/bash
#
# (c) michael.wellner@de.ibm.com 2016. Generated by BashDSL Script Generator.
#
# This script Sets up the local project maven repository with RTC dependencies.
#
# TODO
#
# Usage:
# setup-repo.sh [ -h | --help | OPTIONS ]
#
# Options:
#   -d|--dependencies
#     Public Maven dependencies which sould be used instead of downlaoded ones.
#   -l|--libs
#     Optional. Default: ../libs.
#     The directory containing the RTC jar dependencies.
#   -r|--repo
#     Optional. Default: ../repo.
#     The project's maven repository.
#   -v|--rtc-version
#     Optional. Default: 6.0.1.
#     The current RTC version - Only needed for produced rtc-java-api pom.
#

# Fail if one of the commands fails
set -e

CURRENTDIR=`pwd`
BASEDIR=$(dirname $0)
DEPENDENCIES=
LIBS=
REPO=
RTC_VERSION=
# DEPENDENCIES="org.apache.james:apache-mime4j:0.6 commons-io:commons-io:1.2 org.apache.httpcomponents:httpclient:4.5 org.apache.httpcomponents:httpclient-cache:4.5 org.apache.httpcomponents:httpclient-win:4.5 org.apache.httpcomponents:httpcore:4.4.1 org.apache.httpcomponents:httpcore-ab:4.4.1 org.apache.httpcomponents:httpcore-nio:4.4.1 org.apache.httpcomponents:httpmime:4.5"
# DEPENDENCIES="org.apache.james:apache-mime4j:0.6 commons-io:commons-io:1.2 org.apache.httpcomponents:httpclient:4.1.2 org.apache.httpcomponents:httpcore-nio:4.1.2 org.apache.httpcomponents:httpmime:4.1.2"

main() {
  cd ${BASEDIR}
  read_variables "$@"
  init_defaults

  # Create Repsository directory if necessary
  mkdir -p ${REPO}

  FILES=(`ls ${LIBS} | grep "com.ibm\|org.eclipse\|net.oauth"`)
  for FILE in "${FILES[@]}"; do
    LIB=`echo ${FILE} | awk -F _ '{ print $1 }'`
    VERSION=`echo ${FILE} | awk -F _ '{ print $2 }' | awk -F ".v" '{ print $1 }'`
    if [ "${VERSION}" == "" ]; then VERSION="1.0.0"; fi

    GROUP=`echo ${LIB} | awk -F . 'BEGIN { OFS = "." }{ print $1, $2, $3 }'`
    ARTIFACT=`echo ${LIB} | awk -F . 'BEGIN { OFS = "-" }{ $1=$2=$3=""; print $0 }' | awk -F "---" '{ print $2 }'`
    if [ "${ARTIFACT}" == "" ]; then ARTIFACT=`echo ${LIB} | awk -F . '{ print $3 }'`; fi
    if [ "${ARTIFACT}" == "" ]; then ARTIFACT=`echo ${LIB} | awk -F . '{ print $2 }'`; fi
    if [ "${ARTIFACT}" == "" ]; then ARTIFACT=`echo ${LIB}`; fi

    install_lib ${GROUP} ${ARTIFACT} ${VERSION} ${LIBS}/${FILE}
    DEPENDENCIES="${DEPENDENCIES} ${GROUP}:${ARTIFACT}:${VERSION}"
  done

  write_pom

  echo "Done. Now you can ..."
  echo "#1) Insert the following repository in your project's pom.xml:"
  echo
  echo "   <repositories>"
  echo "      <repository>"
  echo "         <id>project-repo</id>"
  echo "         <releases>"
  echo "            <enabled>true</enabled>"
  echo "            <checksumPolicy>ignore</checksumPolicy>"
  echo "         </releases>"
  echo "         <snapshots>"
  echo "            <enabled>false</enabled>"
  echo "         </snapshots>"
  echo "         <url>file://\${project.basedir}/repo</url>"
  echo "      </repository>"
  echo "   </repositories>"
  echo
  echo "#2) Insert the following dependency in your project's pom.xml:"
  echo
  echo "  <dependency>"
  echo "     <groupId>com.ibm.rtc</groupId>"
  echo "     <artifactId>rtc-java-api</artifactId>"
  echo "     <version>${RTC_VERSION}</version>"
  echo "     <type>pom</type>"
  echo "  </dependency>"
  echo

  cd ${CURRENTDIR}
}

install_lib() {
  GROUP=$1
  ARTIFACT=$2
  VERSION=$3
  FILE=$4

  echo "Installing ${GROUP}:${ARTIFACT}:${VERSION} from ${FILE} ..."
  mvn install:install-file -DlocalRepositoryPath=${REPO} -DcreateChecksum=true -Dpackaging=jar -Dfile="${FILE}" -DgroupId="${GROUP}" -DartifactId="${ARTIFACT}" -Dversion="${VERSION}"
}

write_pom() {
  mkdir -p ./rtc-java-api
  POM="./rtc-java-api/pom.xml"

  echo "<project>" > ${POM}
  echo >> ${POM}
  echo "   <modelVersion>4.0.0</modelVersion>" >> ${POM}
  echo "   <groupId>com.ibm.rtc</groupId>" >> ${POM}
  echo "   <artifactId>rtc-java-api</artifactId>" >> ${POM}
  echo "   <version>${RTC_VERSION}</version>" >> ${POM}
  echo >> ${POM}
  echo "   <description>RTC Java API Maven dependencies.</description>" >> ${POM}
  echo >> ${POM}
  echo "   <packaging>pom</packaging>" >> ${POM}
  echo "   <dependencies>" >> ${POM}


  DEPS=(`echo ${DEPENDENCIES}`)
  for DEPENDENCY in "${DEPS[@]}"; do
    echo ${DEPENDENCY} | awk -F ':' 'BEGIN { RS = "" ; OFS = "" }{ print "      <dependency>"; print "         <groupId>", $1, "</groupId>"; print "         <artifactId>", $2, "</artifactId>"; print "         <version>", $3, "</version>"; print "      </dependency>" }' >> ${POM}
  done;

  echo "   </dependencies>" >> ${POM}
  echo "</project>" >> ${POM}

  echo "Installing com.ibm.rtc:rtc-java-api:${RTC_VERSION} from ${POM} ..."
  mvn install:install-file -DlocalRepositoryPath=${REPO} -DcreateChecksum=true -Dpackaging=pom -Dfile="${POM}" -DgroupId="com.ibm.rtc" -DartifactId="rtc-java-api" -Dversion="${RTC_VERSION}"
}

init_defaults() {
  if [ -z "${DEPENDENCIES}"]; then
    >&2 echo "Missing required parameter: -d|--dependencies."
    show_help_and_exit 1
  fi;
	if [ -z "${LIBS}" ]; then
	  LIBS="../libs"
	fi;
	if [ -z "${REPO}" ]; then
	  REPO="../repo"
	fi;
  if [ -z "${RTC_VERSION}" ]; then
	  RTC_VERSION="6.0.1"
	fi;
}

read_variables() {
  while [[ $# -gt 0 ]]
  do
    key="$1"
    case $key in
      -d|--dependencies)
        DEPENDENCIES="$2"
        shift # past argument
        shift # past argument
        ;;
      -l|--libs)
        LIBS="$2"
        shift # past argument
        shift # past argument
        ;;
      -r|--repo)
        REPO="$2"
        shift # past argument
        shift # past argument
        ;;
      -v|--rtc-version)
        RTC_VERSION="$2"
        shift # past argument
        shift # past argument
        ;;
      -h|--help)
        show_help_and_exit 0;;
      *)
        >&2 echo "Unkown option $1 with value $2."
        echo
        show_help_and_exit 2
        ;;
    esac
  done

  if [ `which mvn` == "" ]; then
    echo "No Maven installed. Please install maven first."
    show_help_and_exit 3
  fi;
}

show_help_and_exit() {
  echo "This script Sets up the local project maven repository with RTC dependencies."
  echo ""
  echo "TODO"
  echo ""
  echo "Usage:"
  echo "setup-repo.sh [ -h | --help | OPTIONS ]"
  echo ""
  echo "Options:"
  echo "  -d|--dependencies"
  echo "    Public Maven dependencies which sould be used instead of downlaoded ones."
  echo "  -l|--libs"
  echo "    Optional. Default: ../libs."
  echo "    The directory containing the RTC jar dependencies."
  echo "  -r|--repo"
  echo "    Optional. Default: ../repo."
  echo "    The project's maven repository."
  echo "  -v|--rtc-version"
  echo "    Optional. Default: 6.0.1."
  echo "    The current RTC version - Only needed for produced rtc-java-api pom."
  echo

  cd ${CURRENTDIR}
  exit $1
}


main "$@"
